apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverful-study
  namespace: serverful-study-prod
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: serverful-study
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
