apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: serverful-study-simple
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/blair06/serverful-study.git
    targetRevision: HEAD
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: serverful-study
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
