apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: serverful-study-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: serverful-study=ghcr.io/blair06/serverful-study
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/serverful-study.update-strategy: latest
    argocd-image-updater.argoproj.io/serverful-study.allow-tags: regexp:^dev-.*$
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/blair06/serverful-study.git
    targetRevision: HEAD
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: serverful-study-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
