apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app: serverful-study
  version: v1

images:
  - name: ghcr.io/blair/serverful-study
    newTag: latest
