apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverful-study
  namespace: serverful-study-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: serverful-study
          env:
            - name: NODE_ENV
              value: "development"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
